# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'aboutdialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AboutDialog(object):
    def setupUi(self, AboutDialog):
        AboutDialog.setObjectName("AboutDialog")
        AboutDialog.resize(642, 777)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AboutDialog.sizePolicy().hasHeightForWidth())
        AboutDialog.setSizePolicy(sizePolicy)
        AboutDialog.setFocusPolicy(QtCore.Qt.NoFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(":/images/new/icon_NK.svg"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        AboutDialog.setWindowIcon(icon)
        AboutDialog.setAutoFillBackground(False)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(AboutDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(AboutDialog)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding,
            QtWidgets.QSizePolicy.MinimumExpanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.IconLabel = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.IconLabel.sizePolicy().hasHeightForWidth())
        self.IconLabel.setSizePolicy(sizePolicy)
        self.IconLabel.setMinimumSize(QtCore.QSize(500, 161))
        self.IconLabel.setMaximumSize(QtCore.QSize(500, 161))
        self.IconLabel.setText("")
        self.IconLabel.setPixmap(QtGui.QPixmap(":/images/new/icon_Logo_App.svg"))
        self.IconLabel.setObjectName("IconLabel")
        self.horizontalLayout_3.addWidget(self.IconLabel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.label_7.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop
        )
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.label_7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.label_6.setOpenExternalLinks(True)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3.addLayout(self.verticalLayout_7)
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(
            QtWidgets.QFormLayout.AllNonFixedFieldsGrow
        )
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.VersionLabel = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.VersionLabel.setFont(font)
        self.VersionLabel.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.VersionLabel.setText("1.0")
        self.VersionLabel.setObjectName("VersionLabel")
        self.formLayout_2.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.VersionLabel
        )
        self.horizontalLayout_7.addLayout(self.formLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.line_3 = QtWidgets.QFrame(self.frame)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_3.addWidget(self.line_3)
        self.AboutLabel_2 = QtWidgets.QLabel(self.frame)
        self.AboutLabel_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.AboutLabel_2.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop
        )
        self.AboutLabel_2.setWordWrap(True)
        self.AboutLabel_2.setOpenExternalLinks(True)
        self.AboutLabel_2.setTextInteractionFlags(
            QtCore.Qt.LinksAccessibleByKeyboard | QtCore.Qt.LinksAccessibleByMouse
        )
        self.AboutLabel_2.setObjectName("AboutLabel_2")
        self.verticalLayout_3.addWidget(self.AboutLabel_2)
        self.verticalLayout_2.addWidget(self.frame)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout.addItem(spacerItem)
        self.ButtonOK = QtWidgets.QPushButton(AboutDialog)
        self.ButtonOK.setFocusPolicy(QtCore.Qt.TabFocus)
        self.ButtonOK.setDefault(True)
        self.ButtonOK.setObjectName("ButtonOK")
        self.horizontalLayout.addWidget(self.ButtonOK)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(AboutDialog)
        QtCore.QMetaObject.connectSlotsByName(AboutDialog)
        AboutDialog.setTabOrder(self.label_7, self.label_6)
        AboutDialog.setTabOrder(self.label_6, self.label_3)
        AboutDialog.setTabOrder(self.label_3, self.VersionLabel)
        AboutDialog.setTabOrder(self.VersionLabel, self.AboutLabel_2)
        AboutDialog.setTabOrder(self.AboutLabel_2, self.ButtonOK)

    def retranslateUi(self, AboutDialog):
        _translate = QtCore.QCoreApplication.translate
        AboutDialog.setWindowTitle(_translate("AboutDialog", "About"))
        self.IconLabel.setAccessibleDescription(_translate("AboutDialog", "Logo"))
        self.label_7.setText(
            _translate(
                "AboutDialog",
                "<html><head/><body><p>This application allows you to configure your Nitrokey 3.</p></body></html>",
            )
        )
        self.label_6.setText(
            _translate(
                "AboutDialog",
                '<html><head/><body><p><a href="https://www.nitrokey.com/start"><span style=" text-decoration: underline; color:#c80636;">Instructions and help</span></a></p></body></html>',
            )
        )
        self.label_3.setText(_translate("AboutDialog", "App version:"))
        self.AboutLabel_2.setText(
            _translate(
                "AboutDialog",
                '<html><head/><body><p><span style=" font-size:10pt; font-style:italic;">This software is licensed under the </span><a href="http://www.apache.org/licenses/"><span style=" font-size:10pt; font-style:italic; text-decoration: underline; color:#c80636;">Apache License 2.0</span></a><span style=" font-size:10pt; font-style:italic;">.</span></p><p><a href="https://nitrokey.com"><span style=" text-decoration: underline; color:#c80636;">www.nitrokey.com</span></a></p></body></html>',
            )
        )
        self.ButtonOK.setText(_translate("AboutDialog", "OK"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    AboutDialog = QtWidgets.QDialog()
    ui = Ui_AboutDialog()
    ui.setupUi(AboutDialog)
    AboutDialog.show()
    sys.exit(app.exec_())
