# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'insert_Nitrokey.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Insert_Nitrokey(object):
    def setupUi(self, Insert_Nitrokey):
        Insert_Nitrokey.setObjectName("Insert_Nitrokey")
        Insert_Nitrokey.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Insert_Nitrokey)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Insert_Nitrokey)
        font = QtGui.QFont()
        font.setPointSize(23)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.pushButton_ok_insert = QtWidgets.QPushButton(Insert_Nitrokey)
        self.pushButton_ok_insert.setObjectName("pushButton_ok_insert")
        self.verticalLayout.addWidget(self.pushButton_ok_insert)

        self.retranslateUi(Insert_Nitrokey)
        QtCore.QMetaObject.connectSlotsByName(Insert_Nitrokey)

    def retranslateUi(self, Insert_Nitrokey):
        _translate = QtCore.QCoreApplication.translate
        Insert_Nitrokey.setWindowTitle(_translate("Insert_Nitrokey", "Dialog"))
        self.label.setText(_translate("Insert_Nitrokey", "Please insert your Nitrokey"))
        self.pushButton_ok_insert.setText(_translate("Insert_Nitrokey", "Ok"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Insert_Nitrokey = QtWidgets.QDialog()
    ui = Ui_Insert_Nitrokey()
    ui.setupUi(Insert_Nitrokey)
    Insert_Nitrokey.show()
    sys.exit(app.exec_())
