# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'key_generation.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Key_generation(object):
    def setupUi(self, Key_generation):
        Key_generation.setObjectName("Key_generation")
        Key_generation.resize(418, 326)
        Key_generation.setWizardStyle(QtWidgets.QWizard.ClassicStyle)
        self.wizardPage1 = QtWidgets.QWizardPage()
        self.wizardPage1.setObjectName("wizardPage1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.wizardPage1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.wizardPage1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.line = QtWidgets.QFrame(self.wizardPage1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.label = QtWidgets.QLabel(self.wizardPage1)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.groupBox_4 = QtWidgets.QGroupBox(self.wizardPage1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.formLayout_9 = QtWidgets.QFormLayout(self.groupBox_4)
        self.formLayout_9.setObjectName("formLayout_9")
        self.label_33 = QtWidgets.QLabel(self.groupBox_4)
        self.label_33.setObjectName("label_33")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_33)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_34 = QtWidgets.QLabel(self.groupBox_4)
        self.label_34.setObjectName("label_34")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_34)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.label_35 = QtWidgets.QLabel(self.groupBox_4)
        self.label_35.setObjectName("label_35")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_35)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.verticalLayout.addWidget(self.groupBox_4)
        Key_generation.addPage(self.wizardPage1)
        self.wizardPage2 = QtWidgets.QWizardPage()
        self.wizardPage2.setObjectName("wizardPage2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.wizardPage2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.wizardPage2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.wizardPage2)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_32 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        self.label_32.setObjectName("label_32")
        self.gridLayout_3.addWidget(self.label_32, 0, 0, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_4.sizePolicy().hasHeightForWidth())
        self.comboBox_4.setSizePolicy(sizePolicy)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_4, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.wizardPage2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.pushButton_wiz = QtWidgets.QPushButton(self.wizardPage2)
        self.pushButton_wiz.setStyleSheet("QPushButton {\n" "Text-align:left;\n" "}")
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap("images/new/down_arrow.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.pushButton_wiz.setIcon(icon)
        self.pushButton_wiz.setCheckable(True)
        self.pushButton_wiz.setObjectName("pushButton_wiz")
        self.gridLayout_2.addWidget(
            self.pushButton_wiz, 4, 0, 1, 1, QtCore.Qt.AlignBottom
        )
        self.adsettings_key = QtWidgets.QWidget(self.wizardPage2)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.adsettings_key.sizePolicy().hasHeightForWidth()
        )
        self.adsettings_key.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.adsettings_key.setFont(font)
        self.adsettings_key.setObjectName("adsettings_key")
        self.gridLayout = QtWidgets.QGridLayout(self.adsettings_key)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox = QtWidgets.QComboBox(self.adsettings_key)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 0, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.adsettings_key)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 1, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.adsettings_key)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
        self.comboBox_2.setSizePolicy(sizePolicy)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout.addWidget(self.comboBox_2, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.adsettings_key)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.adsettings_key, 5, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.wizardPage2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 1, 0, 1, 1)
        Key_generation.addPage(self.wizardPage2)
        self.wizardPage = QtWidgets.QWizardPage()
        self.wizardPage.setObjectName("wizardPage")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.wizardPage)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.wizardPage)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.line_3 = QtWidgets.QFrame(self.wizardPage)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_3.addWidget(self.line_3)
        self.frame_5 = QtWidgets.QFrame(self.wizardPage)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.frame_5.setFont(font)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.radioButton_3 = QtWidgets.QRadioButton(self.frame_5)
        self.radioButton_3.setObjectName("radioButton_3")
        self.gridLayout_4.addWidget(self.radioButton_3, 1, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_4.addWidget(self.lineEdit, 1, 1, 1, 1)
        self.radioButton_4 = QtWidgets.QRadioButton(self.frame_5)
        self.radioButton_4.setChecked(True)
        self.radioButton_4.setObjectName("radioButton_4")
        self.gridLayout_4.addWidget(self.radioButton_4, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.frame_5)
        self.label_2 = QtWidgets.QLabel(self.wizardPage)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        Key_generation.addPage(self.wizardPage)

        self.retranslateUi(Key_generation)
        QtCore.QMetaObject.connectSlotsByName(Key_generation)

    def retranslateUi(self, Key_generation):
        _translate = QtCore.QCoreApplication.translate
        Key_generation.setWindowTitle(_translate("Key_generation", "Wizard"))
        self.label_4.setText(_translate("Key_generation", "User Information"))
        self.label.setText(
            _translate(
                "Key_generation",
                "The following instructions guide through the generation \n"
                "of OpenPGP keys directly on the Nitrokey.\n"
                "\n"
                " Please provide the needed information.",
            )
        )
        self.groupBox_4.setTitle(_translate("Key_generation", "User ID"))
        self.label_33.setText(_translate("Key_generation", "Real name: "))
        self.label_34.setText(_translate("Key_generation", "Email address:"))
        self.label_35.setText(_translate("Key_generation", "Comment:"))
        self.label_3.setText(
            _translate(
                "Key_generation",
                "Here they can determine the expiration date. \n"
                'In "Advanced Settings", the key type and size \n'
                " can be changed.",
            )
        )
        self.label_32.setText(_translate("Key_generation", "Expires in:"))
        self.comboBox_4.setItemText(0, _translate("Key_generation", "never"))
        self.comboBox_4.setItemText(1, _translate("Key_generation", "1 year"))
        self.comboBox_4.setItemText(2, _translate("Key_generation", "2 years"))
        self.comboBox_4.setItemText(3, _translate("Key_generation", "5 years"))
        self.label_5.setText(_translate("Key_generation", "Key Settings"))
        self.pushButton_wiz.setText(_translate("Key_generation", "Advanced Settings"))
        self.comboBox.setItemText(
            0, _translate("Key_generation", "RSA and RSA (default)")
        )
        self.comboBox.setItemText(1, _translate("Key_generation", "DSA"))
        self.comboBox.setItemText(2, _translate("Key_generation", "ECC"))
        self.label_16.setText(_translate("Key_generation", "Key size:"))
        self.comboBox_2.setItemText(0, _translate("Key_generation", "1024 Bits"))
        self.comboBox_2.setItemText(1, _translate("Key_generation", "2048 Bits"))
        self.comboBox_2.setItemText(2, _translate("Key_generation", "4096 Bits"))
        self.label_8.setText(_translate("Key_generation", "Key type:"))
        self.label_6.setText(_translate("Key_generation", "Backup"))
        self.radioButton_3.setText(_translate("Key_generation", "with Backup:"))
        self.radioButton_4.setText(_translate("Key_generation", "without Backup"))
        self.label_2.setText(
            _translate(
                "Key_generation",
                "We recommend that you only create a backup, \n"
                "if you are sure that you can keep it very secure. \n"
                "It is best practice to never have this key on a \n"
                "regular computer which has connection to the \n"
                "internet, so that the key never gets compromised.",
            )
        )


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Key_generation = QtWidgets.QWizard()
    ui = Ui_Key_generation()
    ui.setupUi(Key_generation)
    Key_generation.show()
    sys.exit(app.exec_())
