# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nitrokeyapp/ui/licensedialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LicenseDialog(object):
    def setupUi(self, LicenseDialog):
        LicenseDialog.setObjectName("LicenseDialog")
        LicenseDialog.resize(614, 432)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(LicenseDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.textEdit = QtWidgets.QPlainTextEdit(LicenseDialog)
        self.textEdit.setAutoFillBackground(False)
        self.textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textEdit.setReadOnly(True)
        self.textEdit.setPlainText("")
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.buttonBox = QtWidgets.QDialogButtonBox(LicenseDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(LicenseDialog)
        self.buttonBox.accepted.connect(LicenseDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(LicenseDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(LicenseDialog)

    def retranslateUi(self, LicenseDialog):
        _translate = QtCore.QCoreApplication.translate
        LicenseDialog.setWindowTitle(_translate("LicenseDialog", "License information (ESC to Exit)"))
