# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindowtest.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(932, 854)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding,
            QtWidgets.QSizePolicy.MinimumExpanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 110))
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(":/images/new/icon_NK.svg"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(True)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_8 = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(120, 120))
        self.label_8.setMaximumSize(QtCore.QSize(1200, 70))
        self.label_8.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_8.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(":/images/new/icon_Logo_App.svg"))
        self.label_8.setIndent(1)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.formFrame = QtWidgets.QFrame(self.centralWidget)
        self.formFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.formFrame.setBaseSize(QtCore.QSize(12, 10))
        self.formFrame.setObjectName("formFrame")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.formFrame)
        self.horizontalLayout_10.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem = QtWidgets.QSpacerItem(
            40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_10.addItem(spacerItem)
        self.btn_dial_quit = QtWidgets.QPushButton(self.formFrame)
        self.btn_dial_quit.setStyleSheet(
            "#upLeft { background-color: transparent; border-image: url(:/images/new/icon_safe.svg); background: none; border: none; background-repeat: none; }"
        )
        self.btn_dial_quit.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(
            QtGui.QPixmap(":/images/new/icon_quit.svg"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.btn_dial_quit.setIcon(icon1)
        self.btn_dial_quit.setObjectName("btn_dial_quit")
        self.horizontalLayout_10.addWidget(self.btn_dial_quit)
        self.btn_dial_lock = QtWidgets.QPushButton(self.formFrame)
        self.btn_dial_lock.setStyleSheet(
            "#upLeft { background-color: transparent; border-image: url(:/images/new/icon_safe.svg); background: none; border: none; background-repeat: none; }"
        )
        self.btn_dial_lock.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(
            QtGui.QPixmap(":/images/new/icon_unsafe.svg"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.btn_dial_lock.setIcon(icon2)
        self.btn_dial_lock.setObjectName("btn_dial_lock")
        self.horizontalLayout_10.addWidget(self.btn_dial_lock)
        self.btn_dial_help = QtWidgets.QPushButton(self.formFrame)
        self.btn_dial_help.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_dial_help.setMouseTracking(False)
        self.btn_dial_help.setStyleSheet("")
        self.btn_dial_help.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(
            QtGui.QPixmap("images/new/icon_fragezeichen.svg"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.btn_dial_help.setIcon(icon3)
        self.btn_dial_help.setObjectName("btn_dial_help")
        self.horizontalLayout_10.addWidget(self.btn_dial_help)
        self.pushButton_2 = QtWidgets.QPushButton(self.formFrame)
        self.pushButton_2.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(
            QtGui.QPixmap("images/new/icon_about_nitrokey.svg"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.pushButton_2.setIcon(icon4)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_10.addWidget(self.pushButton_2)
        self.verticalLayout.addWidget(self.formFrame)
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding,
            QtWidgets.QSizePolicy.MinimumExpanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_5.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.gridLayout_5.addItem(spacerItem1, 2, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.gridLayout_5.addItem(spacerItem2, 0, 1, 1, 1)
        self.btn_dial_PWS = QtWidgets.QPushButton(self.tab_5)
        self.btn_dial_PWS.setEnabled(True)
        self.btn_dial_PWS.setStyleSheet("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(
            QtGui.QPixmap(":/images/new/icon_safe.svg"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.btn_dial_PWS.setIcon(icon5)
        self.btn_dial_PWS.setObjectName("btn_dial_PWS")
        self.gridLayout_5.addWidget(self.btn_dial_PWS, 2, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.gridLayout_5.addItem(spacerItem3, 3, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.gridLayout_5.addItem(spacerItem4, 2, 4, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.gridLayout_5.addItem(spacerItem5, 2, 2, 1, 1)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_16.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_16.setSpacing(6)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.checkBox_2 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_16.addWidget(self.checkBox_2, 0, QtCore.Qt.AlignRight)
        self.frame_8 = QtWidgets.QFrame(self.tab)
        self.frame_8.setAutoFillBackground(False)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_11.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_11.setSpacing(6)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_24 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_11.addWidget(self.label_24)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setSpacing(6)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame_8)
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_14.addWidget(self.radioButton_2)
        self.radioButton = QtWidgets.QRadioButton(self.frame_8)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_14.addWidget(self.radioButton)
        self.label_25 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_14.addWidget(self.label_25)
        spacerItem6 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_14.addItem(spacerItem6)
        self.verticalLayout_11.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label = QtWidgets.QLabel(self.frame_8)
        self.label.setObjectName("label")
        self.horizontalLayout_9.addWidget(self.label)
        self.slotComboBox = QtWidgets.QComboBox(self.frame_8)
        self.slotComboBox.setMinimumSize(QtCore.QSize(300, 0))
        self.slotComboBox.setCurrentText("HOTP slot")
        self.slotComboBox.setObjectName("slotComboBox")
        self.slotComboBox.addItem("")
        self.slotComboBox.setItemText(0, "HOTP slot")
        self.horizontalLayout_9.addWidget(self.slotComboBox)
        self.label_2 = QtWidgets.QLabel(self.frame_8)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_9.addWidget(self.label_2)
        self.nameEdit = QtWidgets.QLineEdit(self.frame_8)
        self.nameEdit.setInputMask("")
        self.nameEdit.setMaxLength(15)
        self.nameEdit.setObjectName("nameEdit")
        self.horizontalLayout_9.addWidget(self.nameEdit)
        self.eraseButton = QtWidgets.QPushButton(self.frame_8)
        self.eraseButton.setObjectName("eraseButton")
        self.horizontalLayout_9.addWidget(self.eraseButton)
        self.verticalLayout_11.addLayout(self.horizontalLayout_9)
        self.verticalLayout_16.addWidget(self.frame_8)
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setAutoFillBackground(False)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_21 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_7.addWidget(self.label_21)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setFieldGrowthPolicy(
            QtWidgets.QFormLayout.AllNonFixedFieldsGrow
        )
        self.formLayout_4.setSpacing(6)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.base32RadioButton = QtWidgets.QRadioButton(self.frame)
        self.base32RadioButton.setCheckable(True)
        self.base32RadioButton.setChecked(True)
        self.base32RadioButton.setObjectName("base32RadioButton")
        self.horizontalLayout_6.addWidget(self.base32RadioButton)
        self.hexRadioButton = QtWidgets.QRadioButton(self.frame)
        self.hexRadioButton.setChecked(False)
        self.hexRadioButton.setObjectName("hexRadioButton")
        self.horizontalLayout_6.addWidget(self.hexRadioButton)
        spacerItem7 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_6.addItem(spacerItem7)
        self.l_supportedLength = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.l_supportedLength.setFont(font)
        self.l_supportedLength.setObjectName("l_supportedLength")
        self.horizontalLayout_6.addWidget(self.l_supportedLength)
        self.formLayout_4.setLayout(
            1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_6
        )
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.secretEdit = QtWidgets.QLineEdit(self.frame)
        self.secretEdit.setInputMask("")
        self.secretEdit.setText("")
        self.secretEdit.setMaxLength(200)
        self.secretEdit.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.secretEdit.setClearButtonEnabled(False)
        self.secretEdit.setObjectName("secretEdit")
        self.verticalLayout_6.addWidget(self.secretEdit)
        self.labelNotify = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.labelNotify.setFont(font)
        self.labelNotify.setObjectName("labelNotify")
        self.verticalLayout_6.addWidget(self.labelNotify)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.checkBox = QtWidgets.QCheckBox(self.frame)
        self.checkBox.setEnabled(True)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_4.addWidget(self.checkBox)
        spacerItem8 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_4.addItem(spacerItem8)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.secret_key_generated_len = QtWidgets.QSpinBox(self.frame)
        self.secret_key_generated_len.setMinimum(10)
        self.secret_key_generated_len.setMaximum(40)
        self.secret_key_generated_len.setProperty("value", 40)
        self.secret_key_generated_len.setObjectName("secret_key_generated_len")
        self.horizontalLayout_3.addWidget(self.secret_key_generated_len)
        self.randomSecretButton = QtWidgets.QPushButton(self.frame)
        self.randomSecretButton.setAccessibleDescription("")
        self.randomSecretButton.setObjectName("randomSecretButton")
        self.horizontalLayout_3.addWidget(self.randomSecretButton)
        self.btn_copyToClipboard = QtWidgets.QPushButton(self.frame)
        self.btn_copyToClipboard.setObjectName("btn_copyToClipboard")
        self.horizontalLayout_3.addWidget(self.btn_copyToClipboard)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.formLayout_4.setLayout(
            2, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_6
        )
        self.verticalLayout_7.addLayout(self.formLayout_4)
        self.label_26 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.label_26.setFont(font)
        self.label_26.setWordWrap(True)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_7.addWidget(self.label_26)
        self.verticalLayout_16.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.tab)
        self.frame_2.setAutoFillBackground(False)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_9.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_9.setSpacing(6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_22 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_9.addWidget(self.label_22)
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setFieldGrowthPolicy(
            QtWidgets.QFormLayout.AllNonFixedFieldsGrow
        )
        self.formLayout_5.setSpacing(6)
        self.formLayout_5.setObjectName("formLayout_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.counterEdit = QtWidgets.QLineEdit(self.frame_2)
        self.counterEdit.setInputMask("")
        self.counterEdit.setMaxLength(20)
        self.counterEdit.setObjectName("counterEdit")
        self.horizontalLayout_7.addWidget(self.counterEdit)
        self.setToZeroButton = QtWidgets.QPushButton(self.frame_2)
        self.setToZeroButton.setObjectName("setToZeroButton")
        self.horizontalLayout_7.addWidget(self.setToZeroButton)
        self.setToRandomButton = QtWidgets.QPushButton(self.frame_2)
        self.setToRandomButton.setObjectName("setToRandomButton")
        self.horizontalLayout_7.addWidget(self.setToRandomButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.formLayout_5.setLayout(
            4, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_5
        )
        spacerItem9 = QtWidgets.QSpacerItem(
            20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.formLayout_5.setItem(5, QtWidgets.QFormLayout.FieldRole, spacerItem9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.digits6radioButton = QtWidgets.QRadioButton(self.frame_2)
        self.digits6radioButton.setChecked(True)
        self.digits6radioButton.setObjectName("digits6radioButton")
        self.horizontalLayout_8.addWidget(self.digits6radioButton)
        self.digits8radioButton = QtWidgets.QRadioButton(self.frame_2)
        self.digits8radioButton.setObjectName("digits8radioButton")
        self.horizontalLayout_8.addWidget(self.digits8radioButton)
        spacerItem10 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_8.addItem(spacerItem10)
        self.formLayout_5.setLayout(
            3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_8
        )
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setSpacing(6)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.intervalSpinBox = QtWidgets.QSpinBox(self.frame_2)
        self.intervalSpinBox.setMinimum(1)
        self.intervalSpinBox.setMaximum(65536)
        self.intervalSpinBox.setProperty("value", 30)
        self.intervalSpinBox.setObjectName("intervalSpinBox")
        self.horizontalLayout_15.addWidget(self.intervalSpinBox)
        spacerItem11 = QtWidgets.QSpacerItem(
            40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_15.addItem(spacerItem11)
        self.formLayout_5.setLayout(
            2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_15
        )
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setObjectName("label_5")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.intervalLabel = QtWidgets.QLabel(self.frame_2)
        self.intervalLabel.setObjectName("intervalLabel")
        self.formLayout_5.setWidget(
            2, QtWidgets.QFormLayout.LabelRole, self.intervalLabel
        )
        self.verticalLayout_9.addLayout(self.formLayout_5)
        self.verticalLayout_16.addWidget(self.frame_2)
        spacerItem12 = QtWidgets.QSpacerItem(
            20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding
        )
        self.verticalLayout_16.addItem(spacerItem12)
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_16.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.progressBar = QtWidgets.QProgressBar(self.tab)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        spacerItem13 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout.addItem(spacerItem13)
        self.cancelButton = QtWidgets.QPushButton(self.tab)
        self.cancelButton.setToolTip("")
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.writeButton = QtWidgets.QPushButton(self.tab)
        self.writeButton.setObjectName("writeButton")
        self.horizontalLayout.addWidget(self.writeButton)
        self.verticalLayout_16.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_14.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_14.setSpacing(6)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_4 = QtWidgets.QFrame(self.tab_2)
        self.frame_4.setAutoFillBackground(False)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_12.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_12.setSpacing(6)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_11 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_12.addWidget(self.label_11)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.enableUserPasswordCheckBox = QtWidgets.QCheckBox(self.frame_4)
        self.enableUserPasswordCheckBox.setObjectName("enableUserPasswordCheckBox")
        self.verticalLayout_2.addWidget(self.enableUserPasswordCheckBox)
        self.deleteUserPasswordCheckBox = QtWidgets.QCheckBox(self.frame_4)
        self.deleteUserPasswordCheckBox.setObjectName("deleteUserPasswordCheckBox")
        self.verticalLayout_2.addWidget(self.deleteUserPasswordCheckBox)
        self.verticalLayout_12.addLayout(self.verticalLayout_2)
        self.verticalLayout_14.addWidget(self.frame_4)
        spacerItem14 = QtWidgets.QSpacerItem(
            20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding
        )
        self.verticalLayout_14.addItem(spacerItem14)
        self.line_2 = QtWidgets.QFrame(self.tab_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_14.addWidget(self.line_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem15 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_5.addItem(spacerItem15)
        self.generalCancelButton = QtWidgets.QPushButton(self.tab_2)
        self.generalCancelButton.setObjectName("generalCancelButton")
        self.horizontalLayout_5.addWidget(self.generalCancelButton)
        self.writeGeneralConfigButton = QtWidgets.QPushButton(self.tab_2)
        self.writeGeneralConfigButton.setObjectName("writeGeneralConfigButton")
        self.horizontalLayout_5.addWidget(self.writeGeneralConfigButton)
        self.verticalLayout_14.addLayout(self.horizontalLayout_5)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_19.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_19.setSpacing(6)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.frame_7 = QtWidgets.QFrame(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setAutoFillBackground(False)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_18.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_18.setSpacing(6)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.PWS_EditPassword = QtWidgets.QLineEdit(self.frame_7)
        self.PWS_EditPassword.setObjectName("PWS_EditPassword")
        self.gridLayout.addWidget(self.PWS_EditPassword, 3, 1, 1, 1)
        self.PWS_EditLoginName = QtWidgets.QLineEdit(self.frame_7)
        self.PWS_EditLoginName.setObjectName("PWS_EditLoginName")
        self.gridLayout.addWidget(self.PWS_EditLoginName, 2, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame_7)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 3, 0, 1, 1)
        self.PWS_EditSlotName = QtWidgets.QLineEdit(self.frame_7)
        self.PWS_EditSlotName.setObjectName("PWS_EditSlotName")
        self.gridLayout.addWidget(self.PWS_EditSlotName, 1, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.frame_7)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 2, 0, 1, 1)
        self.PWS_ButtonClearSlot = QtWidgets.QPushButton(self.frame_7)
        self.PWS_ButtonClearSlot.setObjectName("PWS_ButtonClearSlot")
        self.gridLayout.addWidget(self.PWS_ButtonClearSlot, 0, 3, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frame_7)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 1, 0, 1, 1)
        self.PWS_ComboBoxSelectSlot = QtWidgets.QComboBox(self.frame_7)
        self.PWS_ComboBoxSelectSlot.setCurrentText("Static password 0")
        self.PWS_ComboBoxSelectSlot.setObjectName("PWS_ComboBoxSelectSlot")
        self.PWS_ComboBoxSelectSlot.addItem("")
        self.gridLayout.addWidget(self.PWS_ComboBoxSelectSlot, 0, 1, 1, 1)
        self.PWS_ButtonCreatePW = QtWidgets.QPushButton(self.frame_7)
        self.PWS_ButtonCreatePW.setAccessibleDescription("")
        self.PWS_ButtonCreatePW.setObjectName("PWS_ButtonCreatePW")
        self.gridLayout.addWidget(self.PWS_ButtonCreatePW, 3, 3, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.frame_7)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 0, 0, 1, 1)
        self.PWS_CheckBoxHideSecret = QtWidgets.QCheckBox(self.frame_7)
        self.PWS_CheckBoxHideSecret.setEnabled(True)
        self.PWS_CheckBoxHideSecret.setAccessibleName("")
        self.PWS_CheckBoxHideSecret.setChecked(True)
        self.PWS_CheckBoxHideSecret.setObjectName("PWS_CheckBoxHideSecret")
        self.gridLayout.addWidget(self.PWS_CheckBoxHideSecret, 4, 1, 1, 1)
        self.l_chars_left_info = QtWidgets.QLabel(self.frame_7)
        self.l_chars_left_info.setObjectName("l_chars_left_info")
        self.gridLayout.addWidget(self.l_chars_left_info, 0, 2, 1, 1)
        self.l_c_name = QtWidgets.QLabel(self.frame_7)
        self.l_c_name.setText("...")
        self.l_c_name.setAlignment(QtCore.Qt.AlignCenter)
        self.l_c_name.setObjectName("l_c_name")
        self.gridLayout.addWidget(self.l_c_name, 1, 2, 1, 1)
        self.l_c_login = QtWidgets.QLabel(self.frame_7)
        self.l_c_login.setText("...")
        self.l_c_login.setAlignment(QtCore.Qt.AlignCenter)
        self.l_c_login.setObjectName("l_c_login")
        self.gridLayout.addWidget(self.l_c_login, 2, 2, 1, 1)
        self.l_c_password = QtWidgets.QLabel(self.frame_7)
        self.l_c_password.setAlignment(QtCore.Qt.AlignCenter)
        self.l_c_password.setObjectName("l_c_password")
        self.gridLayout.addWidget(self.l_c_password, 3, 2, 1, 1)
        self.verticalLayout_18.addLayout(self.gridLayout)
        self.verticalLayout_19.addWidget(self.frame_7)
        self.l_utf8_info = QtWidgets.QLabel(self.tab_3)
        self.l_utf8_info.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.l_utf8_info.setWordWrap(True)
        self.l_utf8_info.setObjectName("l_utf8_info")
        self.verticalLayout_19.addWidget(self.l_utf8_info)
        spacerItem16 = QtWidgets.QSpacerItem(
            20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding
        )
        self.verticalLayout_19.addItem(spacerItem16)
        self.line_3 = QtWidgets.QFrame(self.tab_3)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_19.addWidget(self.line_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.PWS_ButtonEnable = QtWidgets.QPushButton(self.tab_3)
        self.PWS_ButtonEnable.setObjectName("PWS_ButtonEnable")
        self.horizontalLayout_2.addWidget(self.PWS_ButtonEnable)
        self.PWS_Lock = QtWidgets.QPushButton(self.tab_3)
        self.PWS_Lock.setObjectName("PWS_Lock")
        self.horizontalLayout_2.addWidget(self.PWS_Lock)
        self.PWS_progressBar = QtWidgets.QProgressBar(self.tab_3)
        self.PWS_progressBar.setProperty("value", 42)
        self.PWS_progressBar.setObjectName("PWS_progressBar")
        self.horizontalLayout_2.addWidget(self.PWS_progressBar)
        spacerItem17 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_2.addItem(spacerItem17)
        self.PWS_ButtonClose = QtWidgets.QPushButton(self.tab_3)
        self.PWS_ButtonClose.setObjectName("PWS_ButtonClose")
        self.horizontalLayout_2.addWidget(self.PWS_ButtonClose)
        self.PWS_ButtonSaveSlot = QtWidgets.QPushButton(self.tab_3)
        self.PWS_ButtonSaveSlot.setAutoDefault(True)
        self.PWS_ButtonSaveSlot.setDefault(True)
        self.PWS_ButtonSaveSlot.setObjectName("PWS_ButtonSaveSlot")
        self.horizontalLayout_2.addWidget(self.PWS_ButtonSaveSlot)
        self.verticalLayout_19.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_7)
        self.gridLayout_7.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.btn_dial_EV = QtWidgets.QPushButton(self.tab_7)
        self.btn_dial_EV.setStyleSheet(
            "#upLeft { background-color: transparent; border-image: url(:/images/new/icon_safe.svg); background: none; border: none; background-repeat: none; }"
        )
        icon6 = QtGui.QIcon()
        icon6.addPixmap(
            QtGui.QPixmap(":/images/new/icon_harddrive.svg"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.btn_dial_EV.setIcon(icon6)
        self.btn_dial_EV.setObjectName("btn_dial_EV")
        self.gridLayout_7.addWidget(self.btn_dial_EV, 1, 0, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum
        )
        self.gridLayout_7.addItem(spacerItem18, 1, 1, 1, 1)
        self.btn_dial_HV = QtWidgets.QPushButton(self.tab_7)
        self.btn_dial_HV.setStyleSheet(
            "#upLeft { background-color: transparent; border-image: url(:/images/new/icon_safe.svg); background: none; border: none; background-repeat: none; }"
        )
        self.btn_dial_HV.setIcon(icon6)
        self.btn_dial_HV.setObjectName("btn_dial_HV")
        self.gridLayout_7.addWidget(self.btn_dial_HV, 1, 2, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.gridLayout_7.addItem(spacerItem19, 1, 3, 1, 1)
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_8.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_8.setSpacing(6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_6)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        self.gridLayout_8.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_73 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_73.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_73.setSpacing(6)
        self.verticalLayout_73.setObjectName("verticalLayout_73")
        self.verticalLayout_72 = QtWidgets.QVBoxLayout()
        self.verticalLayout_72.setSpacing(6)
        self.verticalLayout_72.setObjectName("verticalLayout_72")
        self.frame_9 = QtWidgets.QFrame(self.tab_4)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_15.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_15.setSpacing(6)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.gr_general = QtWidgets.QGroupBox(self.frame_9)
        self.gr_general.setObjectName("gr_general")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.gr_general)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setSpacing(6)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.cb_first_run_message = QtWidgets.QCheckBox(self.gr_general)
        self.cb_first_run_message.setObjectName("cb_first_run_message")
        self.horizontalLayout_19.addWidget(self.cb_first_run_message)
        self.cb_show_window_on_start = QtWidgets.QCheckBox(self.gr_general)
        self.cb_show_window_on_start.setObjectName("cb_show_window_on_start")
        self.horizontalLayout_19.addWidget(self.cb_show_window_on_start)
        self.verticalLayout_3.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setSpacing(6)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.cb_hide_main_window_on_close = QtWidgets.QCheckBox(self.gr_general)
        self.cb_hide_main_window_on_close.setChecked(True)
        self.cb_hide_main_window_on_close.setObjectName("cb_hide_main_window_on_close")
        self.horizontalLayout_17.addWidget(self.cb_hide_main_window_on_close)
        self.cb_hide_main_window_on_connection = QtWidgets.QCheckBox(self.gr_general)
        self.cb_hide_main_window_on_connection.setChecked(True)
        self.cb_hide_main_window_on_connection.setObjectName(
            "cb_hide_main_window_on_connection"
        )
        self.horizontalLayout_17.addWidget(self.cb_hide_main_window_on_connection)
        self.verticalLayout_3.addLayout(self.horizontalLayout_17)
        self.cb_show_main_window_on_connection = QtWidgets.QCheckBox(self.gr_general)
        self.cb_show_main_window_on_connection.setChecked(True)
        self.cb_show_main_window_on_connection.setObjectName(
            "cb_show_main_window_on_connection"
        )
        self.verticalLayout_3.addWidget(self.cb_show_main_window_on_connection)
        self.cb_check_symlink = QtWidgets.QCheckBox(self.gr_general)
        self.cb_check_symlink.setChecked(True)
        self.cb_check_symlink.setObjectName("cb_check_symlink")
        self.verticalLayout_3.addWidget(self.cb_check_symlink)
        self.cb_device_connection_message = QtWidgets.QCheckBox(self.gr_general)
        self.cb_device_connection_message.setChecked(True)
        self.cb_device_connection_message.setObjectName("cb_device_connection_message")
        self.verticalLayout_3.addWidget(self.cb_device_connection_message)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(6)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_28 = QtWidgets.QLabel(self.gr_general)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_12.addWidget(self.label_28)
        self.combo_languages = QtWidgets.QComboBox(self.gr_general)
        self.combo_languages.setObjectName("combo_languages")
        self.horizontalLayout_12.addWidget(self.combo_languages)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.verticalLayout_15.addWidget(self.gr_general)
        self.verticalLayout_72.addWidget(self.frame_9)
        self.verticalLayout_71 = QtWidgets.QVBoxLayout()
        self.verticalLayout_71.setSpacing(6)
        self.verticalLayout_71.setObjectName("verticalLayout_71")
        self.groupBox = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.edit_debug_file_path = QtWidgets.QLineEdit(self.groupBox)
        self.edit_debug_file_path.setObjectName("edit_debug_file_path")
        self.gridLayout_3.addWidget(self.edit_debug_file_path, 1, 1, 1, 1)
        self.spin_debug_verbosity = QtWidgets.QSpinBox(self.groupBox)
        self.spin_debug_verbosity.setMaximum(6)
        self.spin_debug_verbosity.setProperty("value", 2)
        self.spin_debug_verbosity.setObjectName("spin_debug_verbosity")
        self.gridLayout_3.addWidget(self.spin_debug_verbosity, 3, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 1, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 3, 0, 1, 1)
        self.cb_debug_enabled = QtWidgets.QCheckBox(self.groupBox)
        self.cb_debug_enabled.setAccessibleName("")
        self.cb_debug_enabled.setObjectName("cb_debug_enabled")
        self.gridLayout_3.addWidget(self.cb_debug_enabled, 0, 0, 1, 1)
        self.btn_select_debug_console = QtWidgets.QPushButton(self.groupBox)
        self.btn_select_debug_console.setObjectName("btn_select_debug_console")
        self.gridLayout_3.addWidget(self.btn_select_debug_console, 1, 2, 1, 1)
        self.btn_select_debug_file_path = QtWidgets.QPushButton(self.groupBox)
        self.btn_select_debug_file_path.setObjectName("btn_select_debug_file_path")
        self.gridLayout_3.addWidget(self.btn_select_debug_file_path, 1, 3, 1, 1)
        self.verticalLayout_71.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.spin_OTP_time = QtWidgets.QSpinBox(self.groupBox_2)
        self.spin_OTP_time.setMinimum(10)
        self.spin_OTP_time.setMaximum(600)
        self.spin_OTP_time.setProperty("value", 120)
        self.spin_OTP_time.setObjectName("spin_OTP_time")
        self.gridLayout_4.addWidget(self.spin_OTP_time, 3, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.groupBox_2)
        self.label_30.setObjectName("label_30")
        self.gridLayout_4.addWidget(self.label_30, 1, 0, 1, 1)
        self.spin_PWS_time = QtWidgets.QSpinBox(self.groupBox_2)
        self.spin_PWS_time.setMinimum(10)
        self.spin_PWS_time.setMaximum(600)
        self.spin_PWS_time.setProperty("value", 60)
        self.spin_PWS_time.setObjectName("spin_PWS_time")
        self.gridLayout_4.addWidget(self.spin_PWS_time, 1, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.groupBox_2)
        self.label_31.setObjectName("label_31")
        self.gridLayout_4.addWidget(self.label_31, 3, 0, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.gridLayout_4.addItem(spacerItem20, 1, 2, 1, 1)
        self.verticalLayout_71.addWidget(self.groupBox_2)
        spacerItem21 = QtWidgets.QSpacerItem(
            20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding
        )
        self.verticalLayout_71.addItem(spacerItem21)
        self.line_10 = QtWidgets.QFrame(self.tab_4)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout_71.addWidget(self.line_10)
        self.verticalLayout_72.addLayout(self.verticalLayout_71)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem22 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_11.addItem(spacerItem22)
        self.btn_cancelSettings = QtWidgets.QPushButton(self.tab_4)
        self.btn_cancelSettings.setObjectName("btn_cancelSettings")
        self.horizontalLayout_11.addWidget(self.btn_cancelSettings)
        self.btn_writeSettings = QtWidgets.QPushButton(self.tab_4)
        self.btn_writeSettings.setObjectName("btn_writeSettings")
        self.horizontalLayout_11.addWidget(self.btn_writeSettings)
        self.verticalLayout_72.addLayout(self.horizontalLayout_11)
        self.verticalLayout_73.addLayout(self.verticalLayout_72)
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setSizeGripEnabled(False)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 932, 22))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.label_10.setBuddy(self.edit_debug_file_path)
        self.label_20.setBuddy(self.spin_debug_verbosity)
        self.label_30.setBuddy(self.spin_debug_verbosity)
        self.label_31.setBuddy(self.spin_debug_verbosity)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(5)
        self.slotComboBox.setCurrentIndex(0)
        self.PWS_ComboBoxSelectSlot.setCurrentIndex(0)
        self.btn_cancelSettings.clicked.connect(MainWindow.hide)
        self.cancelButton.clicked.connect(MainWindow.hide)
        self.cb_debug_enabled.toggled["bool"].connect(
            self.edit_debug_file_path.setEnabled
        )
        self.cb_debug_enabled.toggled["bool"].connect(
            self.spin_debug_verbosity.setEnabled
        )
        self.cb_debug_enabled.toggled["bool"].connect(
            self.btn_select_debug_file_path.setEnabled
        )
        self.generalCancelButton.clicked.connect(MainWindow.hide)
        self.cb_debug_enabled.toggled["bool"].connect(
            self.btn_select_debug_console.setEnabled
        )
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.radioButton_2, self.radioButton)
        MainWindow.setTabOrder(self.radioButton, self.slotComboBox)
        MainWindow.setTabOrder(self.slotComboBox, self.nameEdit)
        MainWindow.setTabOrder(self.nameEdit, self.eraseButton)
        MainWindow.setTabOrder(self.eraseButton, self.base32RadioButton)
        MainWindow.setTabOrder(self.base32RadioButton, self.hexRadioButton)
        MainWindow.setTabOrder(self.hexRadioButton, self.secretEdit)
        MainWindow.setTabOrder(self.secretEdit, self.checkBox)
        MainWindow.setTabOrder(self.checkBox, self.intervalSpinBox)
        MainWindow.setTabOrder(self.intervalSpinBox, self.digits6radioButton)
        MainWindow.setTabOrder(self.digits6radioButton, self.digits8radioButton)
        MainWindow.setTabOrder(self.digits8radioButton, self.counterEdit)
        MainWindow.setTabOrder(self.counterEdit, self.setToZeroButton)
        MainWindow.setTabOrder(self.setToZeroButton, self.setToRandomButton)
        MainWindow.setTabOrder(self.setToRandomButton, self.cancelButton)
        MainWindow.setTabOrder(self.cancelButton, self.writeButton)
        MainWindow.setTabOrder(self.writeButton, self.enableUserPasswordCheckBox)
        MainWindow.setTabOrder(
            self.enableUserPasswordCheckBox, self.deleteUserPasswordCheckBox
        )
        MainWindow.setTabOrder(
            self.deleteUserPasswordCheckBox, self.PWS_ComboBoxSelectSlot
        )
        MainWindow.setTabOrder(self.PWS_ComboBoxSelectSlot, self.PWS_ButtonClearSlot)
        MainWindow.setTabOrder(self.PWS_ButtonClearSlot, self.PWS_EditSlotName)
        MainWindow.setTabOrder(self.PWS_EditSlotName, self.PWS_EditLoginName)
        MainWindow.setTabOrder(self.PWS_EditLoginName, self.PWS_EditPassword)
        MainWindow.setTabOrder(self.PWS_EditPassword, self.PWS_ButtonCreatePW)
        MainWindow.setTabOrder(self.PWS_ButtonCreatePW, self.PWS_CheckBoxHideSecret)
        MainWindow.setTabOrder(self.PWS_CheckBoxHideSecret, self.l_utf8_info)
        MainWindow.setTabOrder(self.l_utf8_info, self.PWS_ButtonEnable)
        MainWindow.setTabOrder(self.PWS_ButtonEnable, self.PWS_Lock)
        MainWindow.setTabOrder(self.PWS_Lock, self.PWS_ButtonClose)
        MainWindow.setTabOrder(self.PWS_ButtonClose, self.PWS_ButtonSaveSlot)
        MainWindow.setTabOrder(self.PWS_ButtonSaveSlot, self.cb_first_run_message)
        MainWindow.setTabOrder(self.cb_first_run_message, self.cb_show_window_on_start)
        MainWindow.setTabOrder(self.cb_show_window_on_start, self.cb_check_symlink)
        MainWindow.setTabOrder(self.cb_check_symlink, self.cb_device_connection_message)
        MainWindow.setTabOrder(
            self.cb_device_connection_message, self.cb_show_main_window_on_connection
        )
        MainWindow.setTabOrder(
            self.cb_show_main_window_on_connection,
            self.cb_hide_main_window_on_connection,
        )
        MainWindow.setTabOrder(
            self.cb_hide_main_window_on_connection, self.cb_hide_main_window_on_close
        )
        MainWindow.setTabOrder(self.cb_hide_main_window_on_close, self.combo_languages)
        MainWindow.setTabOrder(self.combo_languages, self.cb_debug_enabled)
        MainWindow.setTabOrder(self.cb_debug_enabled, self.edit_debug_file_path)
        MainWindow.setTabOrder(self.edit_debug_file_path, self.btn_select_debug_console)
        MainWindow.setTabOrder(
            self.btn_select_debug_console, self.btn_select_debug_file_path
        )
        MainWindow.setTabOrder(
            self.btn_select_debug_file_path, self.spin_debug_verbosity
        )
        MainWindow.setTabOrder(self.spin_debug_verbosity, self.spin_PWS_time)
        MainWindow.setTabOrder(self.spin_PWS_time, self.spin_OTP_time)
        MainWindow.setTabOrder(self.spin_OTP_time, self.btn_cancelSettings)
        MainWindow.setTabOrder(self.btn_cancelSettings, self.btn_writeSettings)
        MainWindow.setTabOrder(self.btn_writeSettings, self.writeGeneralConfigButton)
        MainWindow.setTabOrder(self.writeGeneralConfigButton, self.generalCancelButton)
        MainWindow.setTabOrder(self.generalCancelButton, self.secret_key_generated_len)
        MainWindow.setTabOrder(self.secret_key_generated_len, self.randomSecretButton)
        MainWindow.setTabOrder(self.randomSecretButton, self.btn_copyToClipboard)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Nitrokey App"))
        self.btn_dial_PWS.setText(_translate("MainWindow", "Unlock Password Safe"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Overview")
        )
        self.checkBox_2.setText(_translate("MainWindow", "Advanced mode"))
        self.label_24.setText(_translate("MainWindow", "Manage slots"))
        self.radioButton_2.setAccessibleName(
            _translate("MainWindow", "Select slot type: TOTP")
        )
        self.radioButton_2.setAccessibleDescription(
            _translate(
                "MainWindow",
                "(Recommendation: Use TOTP for web applications and HOTP for local applications)",
            )
        )
        self.radioButton_2.setText(_translate("MainWindow", "TOTP"))
        self.radioButton.setAccessibleName(
            _translate("MainWindow", "Select slot type: HOTP")
        )
        self.radioButton.setAccessibleDescription(
            _translate(
                "MainWindow",
                "(Recommendation: Use TOTP for web applications and HOTP for local applications)",
            )
        )
        self.radioButton.setText(_translate("MainWindow", "HOTP"))
        self.label_25.setText(
            _translate(
                "MainWindow",
                "(Recommendation: Use TOTP for web applications and HOTP for local applications)",
            )
        )
        self.label.setText(_translate("MainWindow", "Slot:"))
        self.slotComboBox.setAccessibleName(
            _translate("MainWindow", "Select OTP slot number")
        )
        self.label_2.setText(_translate("MainWindow", "Name:"))
        self.nameEdit.setAccessibleName(_translate("MainWindow", "Slot name"))
        self.eraseButton.setText(_translate("MainWindow", "Erase Slot"))
        self.label_21.setText(_translate("MainWindow", "Secret key"))
        self.label_4.setText(_translate("MainWindow", "Input format:"))
        self.base32RadioButton.setToolTip(
            _translate("MainWindow", 'Example: "ZR3M5I..."')
        )
        self.base32RadioButton.setAccessibleName(
            _translate("MainWindow", "Secret input format: base32")
        )
        self.base32RadioButton.setText(_translate("MainWindow", "Base32"))
        self.hexRadioButton.setToolTip(
            _translate("MainWindow", 'Example: "A3911C05..." (remove any 0x prefix)')
        )
        self.hexRadioButton.setAccessibleName(
            _translate("MainWindow", "Secret input format: hex")
        )
        self.hexRadioButton.setText(_translate("MainWindow", "Hex"))
        self.l_supportedLength.setAccessibleName(
            _translate(
                "MainWindow",
                "Entered OTP 'Secret Key' string is longer than supported by this device",
            )
        )
        self.l_supportedLength.setAccessibleDescription(
            _translate("MainWindow", "Label shown when the OTP secret key is too long")
        )
        self.l_supportedLength.setText(
            _translate(
                "MainWindow",
                "<html><head/><body><p><span style=\" font-weight:600; color:#a40000;\">Entered OTP 'Secret Key' string is longer than supported by this device</span></p></body></html>",
            )
        )
        self.label_3.setToolTip(
            _translate(
                "MainWindow",
                "<html><head/><body><p>The secret is provided by your service provider you may want to login or can be configured in your local application which you may want to login to.</p></body></html>",
            )
        )
        self.label_3.setText(_translate("MainWindow", "Secret Key:"))
        self.secretEdit.setToolTip(
            _translate(
                "MainWindow",
                "The secret is provided by your service provider you may want to login or can be configured in your local application which you may want to login to.",
            )
        )
        self.secretEdit.setAccessibleName(_translate("MainWindow", "OTP secret key"))
        self.secretEdit.setAccessibleDescription(
            _translate(
                "MainWindow",
                "Note: 2nd factors aren't protected against physical attacks. Change all OTP secrets in case you loose the Nitrokey.",
            )
        )
        self.secretEdit.setPlaceholderText(
            _translate("MainWindow", "********************************")
        )
        self.labelNotify.setText(_translate("MainWindow", "Secret copied to clipboard"))
        self.checkBox.setToolTip(
            _translate(
                "MainWindow",
                "<html><head/><body><p>Hide or show the secret.</p></body></html>",
            )
        )
        self.checkBox.setText(_translate("MainWindow", "Hide secret"))
        self.label_7.setText(
            _translate("MainWindow", "Generated secret target length (bytes):")
        )
        self.secret_key_generated_len.setAccessibleName(
            _translate("MainWindow", "TOTP interval value")
        )
        self.randomSecretButton.setToolTip(
            _translate(
                "MainWindow",
                "After generating a random secret, you would need to copy it into your application or service where you want to login to.",
            )
        )
        self.randomSecretButton.setText(
            _translate("MainWindow", "Generate random secret")
        )
        self.btn_copyToClipboard.setToolTip(
            _translate("MainWindow", "Copy secret to clipboard")
        )
        self.btn_copyToClipboard.setText(_translate("MainWindow", "Copy to clipboard"))
        self.label_26.setText(
            _translate(
                "MainWindow",
                "Note: 2<sup>nd</sup> factors aren't protected against physical attacks. Change all OTP secrets in case you loose the Nitrokey.",
            )
        )
        self.label_22.setText(_translate("MainWindow", "Parameters"))
        self.counterEdit.setAccessibleName(
            _translate("MainWindow", "HOTP moving factor seed")
        )
        self.counterEdit.setText(_translate("MainWindow", "00000000000000000000"))
        self.setToZeroButton.setAccessibleName(
            _translate("MainWindow", "Set HOTP counter to zero")
        )
        self.setToZeroButton.setText(_translate("MainWindow", "Set to zero"))
        self.setToRandomButton.setAccessibleName(
            _translate("MainWindow", "Set HOTP counter to random value")
        )
        self.setToRandomButton.setText(_translate("MainWindow", "Set to random"))
        self.digits6radioButton.setAccessibleName(
            _translate("MainWindow", "OTP code length: 6 digits")
        )
        self.digits6radioButton.setText(_translate("MainWindow", "6 digits"))
        self.digits8radioButton.setAccessibleName(
            _translate("MainWindow", "OTP code length:  8 digits")
        )
        self.digits8radioButton.setText(_translate("MainWindow", "8 digits"))
        self.intervalSpinBox.setAccessibleName(
            _translate("MainWindow", "TOTP interval value")
        )
        self.label_6.setText(_translate("MainWindow", "Moving factor seed:"))
        self.label_5.setText(_translate("MainWindow", "HOTP length:"))
        self.intervalLabel.setText(_translate("MainWindow", "TOTP interval:"))
        self.cancelButton.setText(_translate("MainWindow", "Cancel"))
        self.writeButton.setText(_translate("MainWindow", "Save"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab),
            _translate("MainWindow", "OTP Slot Configuration"),
        )
        self.label_11.setText(_translate("MainWindow", "OTP Password settings"))
        self.enableUserPasswordCheckBox.setText(
            _translate(
                "MainWindow",
                "Protect OTP by user PIN (will be requested on first use each session)",
            )
        )
        self.deleteUserPasswordCheckBox.setText(
            _translate(
                "MainWindow",
                "Forget user PIN after 10 minutes (if unchecked user PIN will remain in memory until application exits)",
            )
        )
        self.generalCancelButton.setText(_translate("MainWindow", "Cancel"))
        self.writeGeneralConfigButton.setText(_translate("MainWindow", "Save"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "OTP General")
        )
        self.PWS_EditPassword.setAccessibleName(_translate("MainWindow", "Password:"))
        self.PWS_EditLoginName.setAccessibleName(
            _translate("MainWindow", "Login name:")
        )
        self.label_19.setText(_translate("MainWindow", "Password:"))
        self.PWS_EditSlotName.setAccessibleName(_translate("MainWindow", "Slot name:"))
        self.label_18.setText(_translate("MainWindow", "Login name:"))
        self.PWS_ButtonClearSlot.setAccessibleName(
            _translate("MainWindow", "Erase Password Safe slot")
        )
        self.PWS_ButtonClearSlot.setText(_translate("MainWindow", "Erase Slot"))
        self.label_17.setText(_translate("MainWindow", "Slot name:"))
        self.PWS_ComboBoxSelectSlot.setAccessibleName(
            _translate("MainWindow", "Password Safe slot number")
        )
        self.PWS_ComboBoxSelectSlot.setItemText(
            0, _translate("MainWindow", "Static password 0")
        )
        self.PWS_ButtonCreatePW.setText(
            _translate("MainWindow", "Generate random password")
        )
        self.label_16.setText(_translate("MainWindow", "Slot:"))
        self.PWS_CheckBoxHideSecret.setText(_translate("MainWindow", "Hide secret"))
        self.l_chars_left_info.setText(_translate("MainWindow", "Characters left:"))
        self.l_c_password.setText(_translate("MainWindow", "..."))
        self.l_utf8_info.setText(
            _translate(
                "MainWindow",
                "<html><head/><body><p>Password Safe fields support UTF8 data. It means that you can use your national characters here. Please remember however that non-English characters could take more space (up to 4 characters). The counters next to each field are to inform how much more standard English characters can given field accept.</p></body></html>",
            )
        )
        self.PWS_ButtonEnable.setText(_translate("MainWindow", "Unlock Password Safe"))
        self.PWS_Lock.setText(_translate("MainWindow", "Lock Device"))
        self.PWS_ButtonClose.setText(_translate("MainWindow", "Cancel"))
        self.PWS_ButtonSaveSlot.setText(_translate("MainWindow", "Save"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_3),
            _translate("MainWindow", "Password Safe"),
        )
        self.btn_dial_EV.setText(_translate("MainWindow", "Unlock Encrypted Volume"))
        self.btn_dial_HV.setText(_translate("MainWindow", "Unlock Hidden Volume"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "Storage")
        )
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "erstes Ding"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Neue Zeile"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Neue Zeile"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Stuff"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Neue Spalte"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Copy"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "FIDO2")
        )
        self.gr_general.setTitle(_translate("MainWindow", "General"))
        self.cb_first_run_message.setText(
            _translate("MainWindow", "Show first-run message")
        )
        self.cb_show_window_on_start.setText(
            _translate("MainWindow", "Show main window on start")
        )
        self.cb_hide_main_window_on_close.setText(
            _translate("MainWindow", "Do not quit when the main window is closed")
        )
        self.cb_hide_main_window_on_connection.setText(
            _translate("MainWindow", "Hide main window when device disconnects")
        )
        self.cb_show_main_window_on_connection.setText(
            _translate("MainWindow", "Show main window when device connects")
        )
        self.cb_check_symlink.setText(
            _translate(
                "MainWindow",
                "Show warning when no partitions could be detected on Encrypted Volume (Linux only)",
            )
        )
        self.cb_device_connection_message.setText(
            _translate(
                "MainWindow", "Show message about device's connection / disconnection"
            )
        )
        self.label_28.setText(
            _translate(
                "MainWindow",
                "<html><head/><body><p>Translation file (needs restart)</p></body></html>",
            )
        )
        self.combo_languages.setAccessibleName(
            _translate("MainWindow", "Translation file (needs restart)")
        )
        self.groupBox.setTitle(_translate("MainWindow", "Debug log settings"))
        self.edit_debug_file_path.setAccessibleName(
            _translate("MainWindow", "Path for debug log file:")
        )
        self.spin_debug_verbosity.setAccessibleName(
            _translate("MainWindow", "Verbosity level:")
        )
        self.label_10.setText(_translate("MainWindow", "Path for debug log file:"))
        self.label_20.setText(_translate("MainWindow", "Verbosity level:"))
        self.cb_debug_enabled.setText(_translate("MainWindow", "Logging enabled"))
        self.btn_select_debug_console.setText(
            _translate("MainWindow", "Log to console")
        )
        self.btn_select_debug_file_path.setText(_translate("MainWindow", "Select path"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Clipboard settings"))
        self.spin_OTP_time.setAccessibleName(
            _translate(
                "MainWindow", "Time to store OTP secrets in clipboard (in seconds):"
            )
        )
        self.label_30.setText(
            _translate(
                "MainWindow",
                "Time to store Password Safe secrets in clipboard (in seconds):",
            )
        )
        self.spin_PWS_time.setAccessibleName(
            _translate(
                "MainWindow",
                "TIme to store Password Safe secrets in clipboard (in seconds):",
            )
        )
        self.label_31.setText(
            _translate(
                "MainWindow", "Time to store OTP secrets in clipboard (in seconds):"
            )
        )
        self.btn_cancelSettings.setText(_translate("MainWindow", "Cancel"))
        self.btn_writeSettings.setText(_translate("MainWindow", "Save"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Settings")
        )
