# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nitrokeyapp/ui/stick20debugdialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DebugDialog(object):
    def setupUi(self, DebugDialog):
        DebugDialog.setObjectName("DebugDialog")
        DebugDialog.resize(793, 789)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/new/icon_NK.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DebugDialog.setWindowIcon(icon)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(DebugDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.TextGUI = QtWidgets.QPlainTextEdit(DebugDialog)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.TextGUI.setFont(font)
        self.TextGUI.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.TextGUI.setReadOnly(True)
        self.TextGUI.setPlainText("")
        self.TextGUI.setObjectName("TextGUI")
        self.verticalLayout.addWidget(self.TextGUI)
        self.buttonBox = QtWidgets.QDialogButtonBox(DebugDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(DebugDialog)
        self.buttonBox.accepted.connect(DebugDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(DebugDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DebugDialog)

    def retranslateUi(self, DebugDialog):
        _translate = QtCore.QCoreApplication.translate
        DebugDialog.setWindowTitle(_translate("DebugDialog", "Debug Log"))
        self.TextGUI.setPlaceholderText(_translate("DebugDialog", "Debug Log"))
import resources_rc
